import type { ComponentType } from 'react'
import {
  IpCloudSunHail,
  IpComparison,
  IpHeadSideMask,
  IpShip,
  IpTear,
  IpTemperatureHalf,
  IpThunderstorm,
  IpWind,
} from '@/src/components/icons'
import type { TimeseriesElementGroup, TimeseriesElementItem } from './types'

type GroupIcon = NonNullable<TimeseriesElementGroup['icon']>

function groupIcon(Icon: ComponentType<{ className: string }>): GroupIcon {
  return Icon as GroupIcon
}

const UNIT_BY_KEY: Record<string, string> = {
  precipitation: 'mm',
  snow: 'cm',
  temperature: '°C',
  visibility: 'km',
  wave: 'm',
  wind: 'm/s',
  windgust: 'm/s',
}

function item(partial: TimeseriesElementItem): TimeseriesElementItem {
  return {
    ...partial,
    unit:
      partial.unit ??
      (partial.unitKey ? UNIT_BY_KEY[partial.unitKey] : undefined),
  }
}

/**
 * Default element groups, carried over from ImWeather `TIMESERIES.groups`.
 * Custom activity groups are omitted. Daypart-only rows are omitted.
 * Titles are resolved English strings.
 */
export const DEFAULT_TIMESERIES_ELEMENT_GROUPS: TimeseriesElementGroup[] = [
  {
    key: 'overview',
    title: 'Overview',
    icon: groupIcon(IpComparison),
    items: [
      item({
        slug: 'overview_weathericon',
        title: 'Weather icon',
        element: 'weathericon',
        view: 'ICON',
      }),
      item({
        slug: 'overview_temperature',
        title: 'Temperature',
        element: 'temperature',
        level: '2m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'overview_dewpoint',
        title: 'Dewpoint',
        element: 'dewpoint',
        level: '2m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'overview_precipitationrate',
        title: 'Precipitation rate',
        element: 'precipitationrate',
        unitKey: 'precipitation',
        view: 'VALUE',
        decimals: 1,
      }),
      item({
        slug: 'overview_precipitationtype',
        title: 'Precipitation type',
        element: 'precipitationtype',
        unit: '-',
        view: 'PRECIPITATION_TYPE',
      }),
      item({
        slug: 'overview_precip',
        title: 'Precipitation',
        element: 'precipitation',
        unitKey: 'precipitation',
        view: 'VALUE',
      }),
      item({
        slug: 'overview_sunpercentage',
        title: 'Sun/Clearance percentage',
        element: 'sunpercentage',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'overview_cloudcovertotal',
        title: 'Total cloud cov',
        element: 'cloudcovertotal',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'overview_winddirection',
        title: 'Wind direction',
        element: 'winddirection',
        level: '10m',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'overview_windspeed',
        title: 'Wind',
        element: 'windspeed',
        level: '10m',
        unitKey: 'wind',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'overview_windgust',
        title: 'Wind gusts',
        element: 'windgust',
        level: '10m',
        unitKey: 'windgust',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'overview_meansealevel',
        title: 'Mean sea level pressure',
        element: 'pressure_meansealevel',
        unit: 'hPa',
        view: 'VALUE',
      }),
    ],
  },
  {
    key: 'temperature',
    title: 'Temperature',
    icon: groupIcon(IpTemperatureHalf),
    items: [
      item({
        slug: 'temperature_temperatureapparent',
        title: 'Feels like temperature',
        element: 'temperatureapparent',
        level: '2m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'temperature_temperature_surface',
        title: 'Temperature',
        element: 'temperature',
        level: 'surface',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'temperature_temperature',
        title: 'Temperature',
        element: 'temperature',
        level: '2m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'temperature_temperature_50m',
        title: 'Temperature',
        element: 'temperature',
        level: '50m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'temperature_temperature_100m',
        title: 'Temperature',
        element: 'temperature',
        level: '100m',
        unitKey: 'temperature',
        decimals: 0,
      }),
      item({
        slug: 'temperature_temperature_200m',
        title: 'Temperature',
        element: 'temperature',
        level: '200m',
        unitKey: 'temperature',
        decimals: 0,
      }),
      item({
        slug: 'temperature_temperature_300m',
        title: 'Temperature',
        element: 'temperature',
        level: '300m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'temperature_temperaturemax_2m',
        title: 'Temperature max',
        element: 'temperaturemax',
        level: '2m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'temperature_temperaturemin_2m',
        title: 'Temperature min',
        element: 'temperaturemin',
        level: '2m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'temperature_dewpoint',
        title: 'Dewpoint',
        element: 'dewpoint',
        level: '2m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
    ],
  },
  {
    key: 'moisture',
    title: 'Moisture / Clouds',
    icon: groupIcon(IpTear),
    items: [
      item({
        slug: 'moisture_dewpoint',
        title: 'Dewpoint',
        element: 'dewpoint',
        level: '2m',
        unitKey: 'temperature',
        view: 'VALUE',
      }),
      item({
        slug: 'moisture_relativehumidity',
        title: 'Relative humidity',
        element: 'relativehumidity',
        level: '2m',
        unit: '%',
        view: 'VALUE_ROUND',
        decimals: 0,
      }),
      item({
        slug: 'moisture_visibility',
        title: 'Visibility',
        element: 'visibility',
        unitKey: 'visibility',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'moisture_cloudcoverlow',
        title: 'Low level cloud cov',
        element: 'cloudcoverlow',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'moisture_cloudcovermiddle',
        title: 'Mid level cloud cov',
        element: 'cloudcovermiddle',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'moisture_cloudcoverhigh',
        title: 'High level cloud cov',
        element: 'cloudcoverhigh',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'moisture_cloudcovershading',
        title: 'Shading clouds',
        element: 'cloudcovershading',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'moisture_cloudcovertotal',
        title: 'Total cloud cov',
        element: 'cloudcovertotal',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'moisture_sunpercentage',
        title: 'Sun/Clearance percentage',
        element: 'sunpercentage',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
    ],
  },
  {
    key: 'wind',
    title: 'Wind',
    icon: groupIcon(IpWind),
    items: [
      item({
        slug: 'wind_windspeed',
        title: 'Wind',
        element: 'windspeed',
        level: '10m',
        unitKey: 'wind',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windspeed_50m',
        title: 'Wind',
        element: 'windspeed',
        level: '50m',
        unitKey: 'wind',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windspeed_100m',
        title: 'Wind',
        element: 'windspeed',
        level: '100m',
        unitKey: 'wind',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windspeed_250hPa',
        title: 'Wind',
        element: 'windspeed',
        level: '250hPa',
        unitKey: 'wind',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windspeed_300hPa',
        title: 'Wind',
        element: 'windspeed',
        level: '300hPa',
        unitKey: 'wind',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windgust',
        title: 'Wind gusts',
        element: 'windgust',
        level: '10m',
        unitKey: 'windgust',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windgust_50m',
        title: 'Wind gusts',
        element: 'windgust',
        level: '50m',
        unitKey: 'windgust',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windgust_100m',
        title: 'Wind gusts',
        element: 'windgust',
        level: '100m',
        unitKey: 'windgust',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windgust_250hPa',
        title: 'Wind gusts',
        element: 'windgust',
        level: '250hPa',
        unitKey: 'windgust',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_windgust_300hPa',
        title: 'Wind gusts',
        element: 'windgust',
        level: '300hPa',
        unitKey: 'windgust',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'wind_winddirection',
        title: 'Wind direction',
        element: 'winddirection',
        level: '10m',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wind_winddirection_50m',
        title: 'Wind direction',
        element: 'winddirection',
        level: '50m',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wind_winddirection_100m',
        title: 'Wind direction',
        element: 'winddirection',
        level: '100m',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wind_winddirection_250hPa',
        title: 'Wind direction',
        element: 'winddirection',
        level: '250hPa',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wind_winddirection_300hPa',
        title: 'Wind direction',
        element: 'winddirection',
        level: '300hPa',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wind_probability_storm',
        title: 'Probability Storm',
        element: 'probability_storm',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
    ],
  },
  {
    key: 'precipitation',
    title: 'Precipitation',
    icon: groupIcon(IpCloudSunHail),
    items: [
      item({
        slug: 'precipitation_precipitationrate',
        title: 'Precipitation rate',
        element: 'precipitationrate',
        unitKey: 'precipitation',
        view: 'VALUE',
      }),
      item({
        slug: 'precipitation_precipitation',
        title: 'Precipitation',
        element: 'precipitation',
        unitKey: 'precipitation',
        view: 'VALUE',
      }),
      item({
        slug: 'precipitation_precipitationtype',
        title: 'Precipitation type',
        element: 'precipitationtype',
        unit: '-',
        view: 'PRECIPITATION_TYPE',
      }),
      item({
        slug: 'precipitation_precipitationaccumulation',
        title: 'Precipitation accumulation',
        element: 'precipitationaccumulation',
        unit: 'mm',
        view: 'VALUE',
      }),
      item({
        slug: 'precipitation_precipprop',
        title: 'Precipitation Probability',
        element: 'probability_precipitation',
        unit: '%',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'precipitation_snowdepth',
        title: 'Snow depth',
        element: 'snowdepth',
        unitKey: 'snow',
        view: 'VALUE',
      }),
    ],
  },
  {
    key: 'stability',
    title: 'Stability',
    icon: groupIcon(IpThunderstorm),
    items: [
      item({
        slug: 'stability_cape',
        title: 'CAPE',
        element: 'cape',
        level: 'mixedlayer',
        unit: 'J/kg',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'stability_cape_unstable',
        title: 'CAPE',
        element: 'cape',
        level: 'mostunstable',
        unit: 'J/kg',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'stability_pressure_surface',
        title: 'Surface pressure',
        element: 'pressure_surface',
        unit: 'hPa',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'stability_pressure_meansealevel',
        title: 'Mean sea level pressure',
        element: 'pressure_meansealevel',
        unit: 'hPa',
        view: 'VALUE',
      }),
    ],
  },
  {
    key: 'airquality',
    title: 'Air quality',
    icon: groupIcon(IpHeadSideMask),
    items: [
      item({
        slug: 'airquality_biomassburning',
        title: 'Wildfire aerosol',
        element: 'biomassburning',
        unit: 'µg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_carbonmonoxide',
        title: 'Carbon monoxide (CO)',
        element: 'carbonmonoxide',
        unit: 'µg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_dust',
        title: 'Desert dust aerosol',
        element: 'dust',
        unit: 'µg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_nitrogendioxide',
        title: 'Nitrogen dioxide (NO2)',
        element: 'nitrogendioxide',
        unit: 'µg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_nitrogenmonoxide',
        title: 'Nitrogen monoxide (NO)',
        element: 'nitrogenmonoxide',
        unit: 'kg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_opticalthickness_aerosol',
        title: 'Aerosol optical thickness',
        element: 'opticalthickness_aerosol',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_opticalthickness_biomassburning',
        title: 'Wildfire aerosol',
        element: 'opticalthickness_biomassburning',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_opticalthickness_dust',
        title: 'Desert dust aerosol',
        element: 'opticalthickness_dust',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_opticalthickness_seasalt',
        title: 'Sea salt aerosol',
        element: 'opticalthickness_seasalt',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_ozone',
        title: 'Ozone (O3)',
        element: 'ozone',
        unit: 'µg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pm1',
        title: 'Particulate matter <1 µm (PM1)',
        element: 'pm1',
        unit: 'µg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pm2p5',
        title: 'Particulate matter <2.5 µm (PM2.5)',
        element: 'pm2p5',
        unit: 'µg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pm10',
        title: 'Particulate matter <10 µm (PM10)',
        element: 'pm10',
        unit: 'µg/m³',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pollen_alder',
        title: 'Alder pollen',
        element: 'pollen_alder',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pollen_birch',
        title: 'Birch pollen',
        element: 'pollen_birch',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pollen_grass',
        title: 'Grass pollen',
        element: 'pollen_grass',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pollen_mugwort',
        title: 'Mugwort pollen',
        element: 'pollen_mugwort',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pollen_olive',
        title: 'Olive pollen',
        element: 'pollen_olive',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_pollen_ragweed',
        title: 'Ragweed pollen',
        element: 'pollen_ragweed',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_sulphurdioxide',
        title: 'Sulphur dioxide (SO2)',
        element: 'sulphurdioxide',
        unit: 'µg/m3',
        level: 'surface',
        view: 'VALUE_ROUND',
      }),
      item({
        slug: 'airquality_uvindex',
        title: 'UV index',
        element: 'uvindex',
      }),
      item({
        slug: 'airquality_uvindexclearsky',
        title: 'Clear sky UV index',
        element: 'uvindexclearsky',
      }),
    ],
  },
  {
    key: 'wave',
    title: 'Maritime',
    icon: groupIcon(IpShip),
    items: [
      item({
        slug: 'wave_windspeed',
        title: 'Wind',
        element: 'windspeed',
        level: '10m',
        unitKey: 'wind',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_winddirection',
        title: 'Wind direction',
        element: 'winddirection',
        level: '10m',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wave_waveheight_significant',
        title: 'Significant wave height',
        element: 'waveheight_significant',
        unitKey: 'wave',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_waveperiod_mean',
        title: 'Mean wave period',
        element: 'waveperiod_mean',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_wavedirection_mean',
        title: 'Mean wave direction',
        element: 'wavedirection_mean',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wave_wavedirection_swell',
        title: 'Swell wave direction',
        element: 'wavedirection_swell',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wave_wavedirection_swell_secondary',
        title: 'Secondary swell direction',
        element: 'wavedirection_swell_secondary',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wave_wavedirection_wind',
        title: 'Wind waves direction',
        element: 'wavedirection_wind',
        unit: '°',
        view: 'DIRECTION',
      }),
      item({
        slug: 'wave_waveheight_swell',
        title: 'Swell height',
        element: 'waveheight_swell',
        unitKey: 'wave',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_waveheight_swell_secondary',
        title: 'Secondary swell height',
        element: 'waveheight_swell_secondary',
        unitKey: 'wave',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_waveheight_wind',
        title: 'Wind waves',
        element: 'waveheight_wind',
        unitKey: 'wave',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_waveperiod_peak',
        title: 'Peak wave period',
        element: 'waveperiod_peak',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_waveperiod_swell',
        title: 'Swell period',
        element: 'waveperiod_swell',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_waveperiod_swell_secondary',
        title: 'Secondary swell period',
        element: 'waveperiod_swell_secondary',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_waveperiod_wind',
        title: 'Wind wave period',
        element: 'waveperiod_wind',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_currentspeed',
        title: 'Current speed',
        element: 'currentspeed',
        unitKey: 'windgust',
        level: 'seasurface',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_currentdirection',
        title: 'Current direction',
        element: 'currentdirection',
        unit: '°',
        view: 'DIRECTION',
        level: 'seasurface',
      }),
      item({
        slug: 'wave_seasurfaceheight',
        title: 'Water level',
        element: 'seasurfaceheight',
        unitKey: 'wave',
        view: 'VALUE',
      }),
      item({
        slug: 'wave_salinity',
        title: 'Salinity',
        element: 'salinity',
        level: 'seasurface',
        view: 'VALUE',
      }),
    ],
  },
]
